//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaCena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cathegory
    {
        public Cathegory()
        {
            this.ProductAds = new HashSet<ProductAd>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CathegoryTypeId { get; set; }
    
        public virtual ICollection<ProductAd> ProductAds { get; set; }
        public virtual CathegoryType CathegoryType { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
